import React, { Component } from 'react';
import SyntaxHighlighter from 'react-syntax-highlighter';
import { ocean } from 'react-syntax-highlighter/styles/hljs';
import JSONPretty from 'react-json-pretty';

class VerifyTxOutProof extends Component {
  constructor(props) {
    super(props);
    this.state = {
      data: 'null'
    };
  }

  handleInputChange(e) {
    let value = e.target.value;
    this.setState({
      proof: value
    });
  }

  handleSubmit(e) {
    this.props.bitbox.Blockchain.verifyTxOutProof(this.state.proof).then((result) => {
      this.setState({
        data: result
      })
    }, (err) => { console.log(err); });
    e.preventDefault();
  }

  render() {
    return (
      <div className="VerifyTxOutProof">
        <h1 className="VerifyTxOutProof-title">VerifyTxOutProof</h1>
        <form className="pure-form pure-form-aligned" onSubmit={this.handleSubmit.bind(this)}>
          <fieldset>
            <div className="pure-control-group">
              <label>Proof</label>
              <input onChange={this.handleInputChange.bind(this)} id="proof" type="text" placeholder="Proof"/>
            </div>
            <div>
              <button type="submit" className="pure-button pure-button-primary">Submit</button>
            </div>
          </fieldset>
        </form>
        <h2>Command Result</h2>
        <JSONPretty id="json-pretty" json={this.state.data}></JSONPretty>
        <h2>RPC Help</h2>
        <SyntaxHighlighter language='bash' style={ocean}>{`
  Verifies that a proof points to a transaction in a block, returning the transaction it commits to and throwing an RPC error if the block is not in our best chain

  Arguments:
  1. "proof"    (string, required) The hex-encoded proof generated by gettxoutproof

  Result:
  ["txid"]      (array, strings) The txid(s) which the proof commits to, or empty array if the proof is invalid
        `}</SyntaxHighlighter>
      </div>
    );
  }
}

export default VerifyTxOutProof;
